services:
  pocket-photo-log-dev:
    build:
      context: .
      target: pocket-photo-log-dev
    command: sh -c "
      npx prisma migrate deploy &&
      npx prisma generate &&
      npx tsx prisma/seed.ts &&
      npm run dev -- --host 0.0.0.0 &
      npx prisma studio --port 5555"
    container_name: pocket-photo-log-dev
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - .node_modules/
        - action: rebuild
          path: package.json
    env_file:
      - .env.development
    environment:
        - NODE_ENV=development
    networks:
      - pocket-photo-log
    ports:
      - 4321:4321 # Web app
      - 5555:5555 # Prisma Studio
    profiles:
      - development
    restart: unless-stopped
    volumes:
      # In development mode we map the local storage folder to the container
      - ./storage:/app/storage
      # Mapped volume for PB migrations
      - ./prisma:/app/prisma:rw

  pocket-photo-log-prod:
    build:
      context: .
      target: pocket-photo-log-prod
    container_name: pocket-photo-log-prod
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=4321
    networks:
      - pocket-photo-log
    ports:
      - 4321:4321
    profiles:
      - production
    restart: unless-stopped
    volumes:
      # Persistent volume for storage
      - pocket-photo-storage:/app/storage

networks:
  pocket-photo-log:
    driver: bridge

volumes:
  pocket-photo-storage:
